config/routes.rb
Appointments::Application.routes.draw do
  resources :tests

  get "home/index"
  resources :appointments
  scope :api do
    get "/appointments(.:format)" => "appointments#index"
    get "/appointments/:id(.:format)" => "appointments#show"
    post "/appointments/" => "appointments#create"
  end
  root to: "home#index"

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validates_presence_of :title, :start, :end
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    render json: Appointment.all
  end

  def show
    render json: Appointment.find(params[:id])
  end

  def create
    @appointment = Appointment.new(params[:appointment])
    logger.info params

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Test was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render action: 'show', status: :created, location: @test }
      else
        format.html { render action: 'new' }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params[:test]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/appointments/new.html.erb
<h1>New test</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/home/index.html.erb
<div class="container" ng-app="Calendar">

<script type="text/ng-template" id="myModalContent.html">

    <div class="modal-header">
        <h3>I'm a modal!</h3>
    </div>

    <div class="modal-body">
        <form name="myForm" ng-controller="FormCtrl">
            <fieldset>
                <label>Title</label>
                <input name="title" ng-model="appointment.title" required>
                <span class="error" ng-show="myForm.title.$error.required">Required!</span><br>

                <label>Description</label>
                <input name="description" ng-model="appointment.description" required>
                <span class="error" ng-show="myForm.description.$error.required">Required!</span><br>
            </fieldset>
            <button class="btn btn-primary" ng-click="ok(appointment)">OK</button>
            <button class="btn btn-warning" ng-click="cancel()">Cancel</button>
         </form>
    </div>
</script>


<div ng-controller="ModalDemoCtrl">
    <button class="btn" ng-click="open()">Open me!</button>
    <div ng-show="selected">Selection from a modal: {{ selected }}</div>
</div>


  <div ng-controller="CalendarCtrl">
    
    <div class="row">

      <div class="span4">
      asdf
      </div>
    
      <button id="open"> Modal </button>
      <div class="span8">
        <div class="alert-success calAlert" ng-show="alertMessage != undefined && alertMessage != ''">
          <h2>{{alertMessage}}</h2>
        </div> 
        <div class="well">
          <div ui-calendar="uiConfig.calendar" ng-model="eventSources">
        </div>
      </div>

    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appointments</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>